CREATE TABLE IF NOT EXISTS articles (
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(128) NOT NULL,
    content TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
