CREATE TABLE IF NOT EXISTS articles (
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(128) NOT NULL DEFAULT "",
    content TEXT,
    created_at INTEGER NOT NULL DEFAULT 1674090479,
    updated_at INTEGER NOT NULL DEFAULT 1674090479
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
